changelog:
  categories:
    - title: ➕ New
      labels: ["new"]
    - title: 🐛 Fixes
      labels: ["fix", "bug"]
    - title: 📖 Documentation
      labels: ["documentation", "docs"]
    - title: 🔗 Dependencies
      labels: ["dependencies"]
    - title: 📦 Other
      labels: ["*"]