changelog:
  categories:
    - title: 🚀 New
      labels: ["new"]
    - title: 🐛 Fixes
      labels: ["fix", "bug"]
    - title: 📝 Dependencies
      labels: ["dependencies"]
    - title: 📦 Uncategorized
      labels: ["*"]