name: Check

on:
  push:
    branches: [ "main" ]
    tags-ignore: [ "**" ]
  pull_request:


jobs:
  gotest:
    strategy:
      matrix:
        go-version: ['1.25.x', 'stable']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: go test -race -shuffle=on -count=10 -timeout=2m ./...


  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version: 'stable'

      - name: Run coverage
        run: go test -coverprofile=coverage.out -covermode=atomic $(go list ./... | grep -v internal/th | grep -v mockapi)

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: destel/rill


  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version: '1.25.x'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
